name: architecture_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_base_architecture_plugin:
    git:
      url: https://github.com/sagarkudecha223/flutter_base_architecture_plugin.git
      ref: master

  cupertino_icons: 1.0.8
  shared_preferences: 2.3.3
  sizer: 3.0.5
  flutter_svg: 2.0.15
  gap: 3.0.1
  permission_handler: 11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner:
  kiwi_generator:
  built_value_generator:

flutter:

  uses-material-design: true

  assets:
    - assets/images/